# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 689381aec9abb0c1eb003af61e9a601fd210a22b41ee7d08f71be1c5d333050345933e219282234c1cba370a9d86da2afcb82f0d7891e81550950d2a323168a1

test:
  secret_key_base: 23e542306c4794ca82849ca384ead87b3d785de989d372041847a3b3ea73f5e4a29d9ee6d920e2f0b4187d1d6b9a9253fa0540deb8ae350d1c1779944b2a4d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
